name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2

      - name: Setup X11  
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mycommand
      
      - name: Setup libs
        run: |
          sudo apt-get install -y libsfml-dev
          sudo apt-get install clang-format

      - name: Check codestyle
        run: |
          git ls-files *.{c,h} | xargs clang-format -i --verbose
          git diff --exit-code

      - name: Build application
        run: make
        
      - name: Build tests
        run: make tests

      - name: run tests
        run: make run_tests
